### ISSUE TITLE
库MainActiviy导入studio报错

### ISSUE THREAD

**Issue by yihuangxing** [typesdk/TypeSDK#1]
Error:Execution failed for task ':mainActivity:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute data@scheme at manifestMerger7343451026144201828.xml requires a placeholder substitution but no value for <qq_appid> is provided.

**Comment by typesdk** [comment]
我们项目工程目前是eclipse的项目结构

**Comment by typesdk** [comment]
报错部分是说你的AndroidManifest中的qq_appid编译不通过，需要你生动替换你们申请的qq_appid，如没有可暫時性填串数字如1234.
