### ISSUE TITLE
android 客户端里面只有jar包没有代码，你也说开源？

### ISSUE THREAD

**Issue by m30102** [typesdk/TypeSDK#2]

**Comment by typesdk** [comment]
开源的是聚会项目工程的代码，您所说的客户端里只有jar包没有代码是指哪个项目工程的?如是自建渠道的项目工程，我们这个项目是不开源的

**Comment by typesdk** [comment]
TypeSDK/TypeSDK_Client/Android/MainActivity/
这里的全是编译好的接入资源，是各个第三方的jar包，比如支付宝，微信等。
所有接入游戏渠道相关的代码都在
TypeSDK/TypeSDK_Package/share/SDK/Channel_SDK

**Comment by m30102** [comment]
客户端接入层  也就是com.type.sdk.TypeSDKHelper 这一层没开源吧

**Comment by typesdk** [comment]
TypeSDKHelper这个类在每个渠道工程下都有
路径：TypeSDK/TypeSDK_Package/share/SDK/Channel_SDK/渠道名称/渠道版本号/MainActivity/src/com/type/sdk/android/
这个类是聚合sdk原生接入的开放接口类，接入文档在官网以下是网址：http://www.typesdk.com/docs/typesdk%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3/%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E5%8E%9F%E7%94%9Fandroid%E9%A1%B9%E7%9B%AE%E6%8E%A5%E5%85%A5 

 

 
全文档目录：
http://www.typesdk.com/documents 

 

请先阅读文档后结合git使用，谢谢

**Comment by Dreamhai** [comment]
没有iOS的吗
